version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
    - '8080:8080'
    command: /bin/sh -c "yarn serve"
  backend:
    build:
      context: ./backend
      target: 'develop-stage-backend'
    ports:
    - '3005:3005'